require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoworkerRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # CoworkerRequest. As you add validations to CoworkerRequest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all coworker_requests as @coworker_requests" do
      coworker_request = CoworkerRequest.create! valid_attributes
      get :index
      assigns(:coworker_requests).should eq([coworker_request])
    end
  end

  describe "GET show" do
    it "assigns the requested coworker_request as @coworker_request" do
      coworker_request = CoworkerRequest.create! valid_attributes
      get :show, :id => coworker_request.id
      assigns(:coworker_request).should eq(coworker_request)
    end
  end

  describe "GET new" do
    it "assigns a new coworker_request as @coworker_request" do
      get :new
      assigns(:coworker_request).should be_a_new(CoworkerRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested coworker_request as @coworker_request" do
      coworker_request = CoworkerRequest.create! valid_attributes
      get :edit, :id => coworker_request.id
      assigns(:coworker_request).should eq(coworker_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoworkerRequest" do
        expect {
          post :create, :coworker_request => valid_attributes
        }.to change(CoworkerRequest, :count).by(1)
      end

      it "assigns a newly created coworker_request as @coworker_request" do
        post :create, :coworker_request => valid_attributes
        assigns(:coworker_request).should be_a(CoworkerRequest)
        assigns(:coworker_request).should be_persisted
      end

      it "redirects to the created coworker_request" do
        post :create, :coworker_request => valid_attributes
        response.should redirect_to(CoworkerRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coworker_request as @coworker_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoworkerRequest.any_instance.stub(:save).and_return(false)
        post :create, :coworker_request => {}
        assigns(:coworker_request).should be_a_new(CoworkerRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoworkerRequest.any_instance.stub(:save).and_return(false)
        post :create, :coworker_request => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coworker_request" do
        coworker_request = CoworkerRequest.create! valid_attributes
        # Assuming there are no other coworker_requests in the database, this
        # specifies that the CoworkerRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoworkerRequest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => coworker_request.id, :coworker_request => {'these' => 'params'}
      end

      it "assigns the requested coworker_request as @coworker_request" do
        coworker_request = CoworkerRequest.create! valid_attributes
        put :update, :id => coworker_request.id, :coworker_request => valid_attributes
        assigns(:coworker_request).should eq(coworker_request)
      end

      it "redirects to the coworker_request" do
        coworker_request = CoworkerRequest.create! valid_attributes
        put :update, :id => coworker_request.id, :coworker_request => valid_attributes
        response.should redirect_to(coworker_request)
      end
    end

    describe "with invalid params" do
      it "assigns the coworker_request as @coworker_request" do
        coworker_request = CoworkerRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoworkerRequest.any_instance.stub(:save).and_return(false)
        put :update, :id => coworker_request.id, :coworker_request => {}
        assigns(:coworker_request).should eq(coworker_request)
      end

      it "re-renders the 'edit' template" do
        coworker_request = CoworkerRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoworkerRequest.any_instance.stub(:save).and_return(false)
        put :update, :id => coworker_request.id, :coworker_request => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coworker_request" do
      coworker_request = CoworkerRequest.create! valid_attributes
      expect {
        delete :destroy, :id => coworker_request.id
      }.to change(CoworkerRequest, :count).by(-1)
    end

    it "redirects to the coworker_requests list" do
      coworker_request = CoworkerRequest.create! valid_attributes
      delete :destroy, :id => coworker_request.id
      response.should redirect_to(coworker_requests_url)
    end
  end

end
